### ISSUE TITLE
Linux build error

### ISSUE THREAD

**Issue by KottV** [Archie3d/qmusic#1]
Greets. I've got this error:

> kv@Kot:/tmp/qmusic/build> make
> [  2%] Built target portaudio
> [  3%] Built target rtmidi
> [ 10%] Built target stk
> [ 10%] Automatic moc for target qwt
> [ 10%] Built target qwt_automoc
> [ 31%] Built target qwt
> [ 31%] Automatic moc for target qtpropertybrowser
> [ 31%] Built target qtpropertybrowser_automoc
> [ 34%] Built target qtpropertybrowser
> [ 35%] Automatic moc for target midi
> [ 35%] Built target midi_automoc
> [ 36%] Built target midi
> [ 36%] Automatic moc for target framework
> [ 36%] Built target framework_automoc
> Scanning dependencies of target framework
> [ 36%] Building CXX object source/framework/CMakeFiles/framework.dir/src/AudioUnitsManager.cpp.o
> /tmp/qmusic/source/framework/src/AudioUnitsManager.cpp:33:46: error: expected primary-expression before ‘*’ token
>  AudioUnitsManager::AudioUnitsManager(QObject *pParent)
>                                               ^
> /tmp/qmusic/source/framework/src/AudioUnitsManager.cpp:33:47: error: ‘pParent’ was not declared in this scope
>  AudioUnitsManager::AudioUnitsManager(QObject *pParent)
>                                                ^~~~~~~
> /tmp/qmusic/source/framework/src/AudioUnitsManager.cpp:33:54: error: cannot call constructor ‘AudioUnitsManager::AudioUnitsManager’ directly [-fpermissive]
>  AudioUnitsManager::AudioUnitsManager(QObject *pParent)
>                                                       ^
> /tmp/qmusic/source/framework/src/AudioUnitsManager.cpp:33:54: note: for a function-style cast, remove the redundant ‘::AudioUnitsManager’
> /tmp/qmusic/source/framework/src/AudioUnitsManager.cpp:39:1: error: expected ‘,’ or ‘;’ before ‘AudioUnitsManager’
>  AudioUnitsManager::~AudioUnitsManager()
>  ^~~~~~~~~~~~~~~~~
> make[2]: *** [source/framework/CMakeFiles/framework.dir/build.make:212: source/framework/CMakeFiles/framework.dir/src/AudioUnitsManager.cpp.o] Ошибка 1
> make[1]: *** [CMakeFiles/Makefile2:584: source/framework/CMakeFiles/framework.dir/all] Ошибка 2
> make: *** [Makefile:161: all] Ошибка 2
>

**Comment by Archie3d** [comment]
Hi,
Thanks for the issue report. I do not regularly check Linux builds. Please pull the latest changes, compiling for Linux should be fine now.

**Comment by KottV** [comment]
Thank you!
